---
language: ruby
cache: bundler
sudo: required
services:
  - docker
script:
  - bundle exec rake validate lint beaker
rvm:
  - 2.2.6
env:
  - BEAKER_set="default"
  - BEAKER_set="default" PUPPET_INSTALL_TYPE="agent" PUPPET_INSTALL_VERSION="1.6.2"
